### ISSUE TITLE
What a successful error curve should look like？

### ISSUE THREAD

**Issue by xiaoyangnihao** [rishikksh20/vae_tacotron2#8]
@rishikksh20 Hi, I use this repo with Blizzard2013 dataset instead of ljspeech dataset with default settings. I want to know whether I am training this vae_model right. or not ?  What a successful error curve should look like with this repo?  The followings are my curves. I wonder whether the difference between kl_loss and reconstruction_loss is too wide. Thanks for any help?

![image](https://user-images.githubusercontent.com/14233490/85940831-8995b200-b951-11ea-9120-ef56b833387b.png)
![image](https://user-images.githubusercontent.com/14233490/85940852-a03c0900-b951-11ea-94c9-cc245a1ee8db.png)
![image](https://user-images.githubusercontent.com/14233490/85940867-b5b13300-b951-11ea-8cc2-273b9e2afedb.png)

**Comment by rishikksh20** [comment]
15k steps from where VAE loss kicked in that's why kl loss increase bit.

**Comment by rishikksh20** [comment]
After loss curve seems ok but stats and kl loss are not converging, for understanding those curve you need to understand the Variational autoencoder training process.. I am not well remembered how should curve be like in I had trained this.

**Comment by xiaoyangnihao** [comment]
> 15k steps from where VAE loss kicked in that's why kl loss increase bit.

Isn't vae loss increased by kl_loss，why do you think it is the opposite, vae_loss ==> kl_loss ?

**Comment by xiaoyangnihao** [comment]
> After loss curve seems ok but stats and kl loss are not converging, for understanding those curve you need to understand the Variational autoencoder training process.. I am not well remembered how should curve be like in I had trained this.

thanks, I will find it out. By the way, I want to make sure that whether the init_vae_weights=0.001 and vae_weight_multiler=0.002 is two big. The mel_loss and kl_loss are not on the same level of magnitude. mel_Loss maybe 0.01, but the kl_loss maybe 300 * 0.3 or 0.
